### PR TITLE
Bullet bug fixed

### PR DESCRIPTION
**Pull request by Abdelilah-Majid**
ok the bullet is now working correctly when pressing arrow down

### CODE REVIEW

**Comment by Abdelilah-Majid** [comment]
hello! is any one online

**Comment by Abdelilah-Majid** [comment]
hey i was wanted to work on a second bullet that you need to press the arrow down to dodge but it need the speed equalizer to work;
because we need to control the two bullets from js so that we have a random bullet chooser(with 2 out of 3 floor bullet and 1 out of 3 flying bullet) script, and for that to work we need to control the bullets with js(I mean to move them with js)

**Comment by Abdelilah-Majid** [comment]
look you should talk more about what you are up to;

you were working on that bullet random position wile am here working on a feature that wont work with that

like don't you use discord or something like that were we can communicate

**Comment by LandonLloyd** [comment]
I have discord. My tag is LHLloyd#0783

**Comment by Abdelilah-Majid** [comment]
i will send you a friend request

**Pull request closed without merging**
