### PR TITLE
controlling the bullets speed

### PR DESCRIPTION
**Pull request by Abdelilah-Majid**
will it was a little tough but i figure it out;

i changed the way we move the bullet from css to js 

sorry i did a mistake i changed the timeoute of checkDead from 10 to 100, can you fix it

the game is working perfectly

look i didnt change much of your code as github is showing its just the code formater(prettier) who re arrange things

and thanks

### CODE REVIEW

**Comment by Abdelilah-Majid** [comment]
ok i fixed the checkDead timing 
and the am_animate_bullet timing

**Comment by Abdelilah-Majid** [comment]
i don't know if its just my pc or every ones pc 
but if you run the game and open the console you will see that the time the bullet takes when it on its full speed is 2409ms
even that the am_checkDead_timer is equal to 15ms 
wish i think is  because my pcs performance or its a DOM limitation

**Comment by LandonLloyd** [comment]
I think we are gonna hold off on this feature for a bit. I am working on getting the hit detection all done and also I need to fix it so that when you crouch the bullet does not bump up.

**Comment by Abdelilah-Majid** [comment]
i dont have that issue

**Comment by Abdelilah-Majid** [comment]
ok what feature or bug you want me to work on

**Comment by Abdelilah-Majid** [comment]
and yah you didn't add me to the contributors

**Comment by LandonLloyd** [comment]
I am working on hit detection right now. If you play the game and hit crouch you will notice the bullet will like 'bump' up. If you could work on that. make the bullet just keep going straight no matter which button the user hits. Try to keep it within the code. You can create new variables and things as needed but don't switch existing variable names. Also when you submit that PR you can add yourself to contributors list in the README file in the same PR. Thanks for working on this!

**Comment by LandonLloyd** [comment]
Thank you for your contribution! If we do decide to add that at a later time I will give you the first go at it!

**Comment by Abdelilah-Majid** [comment]
ok i added my name to the reademe

**Comment by LandonLloyd** [comment]
Alright! I got your name on there. If you wanna work on that project with getting the bullet to stay going straight it is all yours. I am going to close this PR for now though Ok.

**Comment by Abdelilah-Majid** [comment]
i think as the game gets more complex if we added this at a later time its going to be hard to getting the code working with the different score and the bullet mover code
 because instead of counting the score using time i use the position of bullet 
and instead of using css for moving the bullet i use js
so its going to be hard to change a lot of the code base only for this feature

**Comment by LandonLloyd** [comment]
Alright. The game has to be done in 16 days. It is part of a Game Jam. I am going to get the core features down and then I want to add some styling. If we can do that before submission then we will add the bullet speed changer. The PR also has some merging conflicts.

**Comment by Abdelilah-Majid** [comment]
ok i will work on that bullet bug

**Comment by LandonLloyd** [comment]
Thank you for working on this! But it isn't needed right now! The bullet bug is much needed though. Thank you!

**Comment by Abdelilah-Majid** [comment]
you are welcome

**Comment by Abdelilah-Majid** [comment]
ok i fixed the bug;

is there is anything else i can do

**Comment by Abdelilah-Majid** [comment]
i think you should com up with a list of the games basic features and putting them on an issue so we all can know what we need to do;

and to tell each contributor to chose a feature to work on;

i think that will be more efficient;

so every one cold do something, and later on we can decide  wish none necessary features we will work on

**Comment by LandonLloyd** [comment]
Could you open another PR for the bullet bug. Since the other or has conflicts that also makes the bullet bug have a conflict. It will be easier to merge on a new PR. Thanks. I will also start making issues for people to work on. The game is almost done though so I don't know how much more is needed. :smile:

**Pull request closed without merging**
